### ISSUE TITLE
update to new yamllint to support lists in "ignore" config

### ISSUE THREAD

**Issue by SvenStaehs** [actionshub/yamllint#16]
## :person_frowning: Problem Statement

Since the recent release of yamllint 1.29.0 (two days ago), its config file supports using yaml list syntax to specify files to ignore.  

If someone uses the new syntax with this yamllint action, they will receive an error message "invalid config: ignore should contain file patterns"

## :grey_question: Possible Solution

I believe the docker image simply has to be recreated, allowing pip to install the new version of yamllint.  
Then the new tag has to be entered in [action.yml](https://github.com/actionshub/yamllint/blob/main/action.yml#:~:text=docker%3A//ghcr.io/actionshub/yamllint%3Av1.1.0) and a new release pushed.  

## :arrow_heading_up: Describe alternatives you've considered

Alternative is that users use the old syntax of specifying each file spec in a multi-line string. Once they have found out why the error is thrown in the first place.

## :heavy_plus_sign: Additional context

Docs: https://yamllint.readthedocs.io/en/stable/configuration.html#ignoring-paths  
Commit: https://github.com/adrienverge/yamllint/commit/2a904f8fc184a00b9c7b4a05899c8fae7ff13ded#diff-443dfa037d6d01528b63511e2301a7bbb7d2ef8d3dc85b1df3e7fabd8b0d52f5  
Release: https://github.com/adrienverge/yamllint/releases/tag/v1.29.0

**Comment by xorima** [comment]
Thanks for pointing this out @SvenStaehs, I'll try to get this shipped  over the weekend

**Comment by xorima** [comment]
Before I merge, could you @SvenStaehs test running using the branch `release/v1.1.2` instead of your current pinned tag/branch please? (I'd rather not break it for everyone by accident)

**Comment by SvenStaehs** [comment]
Thanks @Xorima! I tested with the old syntax (multi-line string) and with the new list syntax and both worked with release/v1.1.2!
```
ignore: |
  .gitlab-ci.yml
  .gitlab/
```
```
ignore:
  - ".gitlab-ci.yml"
  - ".gitlab/"
  ```

Apart from this my config is really nothing special though, but this part works as expected now 😉

**Comment by xorima** [comment]
Fantastic, now shipped @SvenStaehs
